version: '3.6'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - pg-data:/var/lib/postgresql/data

  server:
    image: node
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://root:password@db:5432/app
      JWT_SECRET: ImAstrongSecret
    working_dir: /usr/src/app
    volumes:
      - ./server:/usr/src/app
    command: npm run dev

volumes:
  pg-data: {}
